version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db_machnet
    environment:
      POSTGRES_USER: machnet_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-machnet:/var/lib/postgresql/data
  machnet_server:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: machnet_server
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres_db
      DB_PORT: "5432"
      DB_USER: machnet_admin
      DB_PASSWORD: password
    volumes:
      - ./server:/app
    command: ["go", "run", "main.go"]
volumes:
  postgres-data-machnet:
