export const sidebarLinks=[
    {
        id:1,
        name:'Home',
        route:'/home',
        icon:'home'
    },
    {
        id:2,
        name:'Transactions',
        route:'/transactions',
        icon:'format_list_bulleted'
    },{
        id:3,
        name:'Cards',
        route:'/cards',
        icon:'home'
    }
]